[build-system]
requires = ["maturin>=1.9,<2"]
build-backend = "maturin"

[project]
name = "pyfjall"
version = "0.1.0"
description = "Python bindings for fjall, an LSM-tree based embeddable key-value storage engine"
readme = "README.md"
requires-python = ">=3.12"
license = "MIT OR Apache-2.0"
classifiers = [
  "Programming Language :: Rust",
  "Programming Language :: Python :: Implementation :: CPython",
  "Topic :: Database",
]
dependencies = []

[project.urls]
Upstream = "https://github.com/fjall-rs/fjall"

[tool.maturin]
python-source = "python"
module-name = "pyfjall._pyfjall"
features = ["pyo3/extension-module"]
strip = true

[dependency-groups]
dev = [
    "maturin>=1.9,<2",
    "pytest>=8",
    "ziglang>=0.16.0",
]

[tool.uv]
cache-keys = [{ file = "pyproject.toml" }, { file = "Cargo.toml" }, { file = "src/**/*.rs" }]
