from os import PathLike
from typing import Iterator, Literal, Optional, Tuple, Union

PersistMode = Literal["buffer", "sync_data", "sync_all"]

class Error(Exception): ...

class Iter(Iterator[Union[bytes, Tuple[bytes, bytes]]]):
    def __iter__(self) -> "Iter": ...
    def __next__(self) -> Union[bytes, Tuple[bytes, bytes]]: ...

class Keyspace:
    @property
    def name(self) -> str: ...
    def insert(self, key: bytes, value: bytes) -> None: ...
    def get(self, key: bytes) -> Optional[bytes]: ...
    def remove(self, key: bytes) -> None: ...
    def contains_key(self, key: bytes) -> bool: ...
    def size_of(self, key: bytes) -> Optional[int]: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...
    def approximate_len(self) -> int: ...
    def disk_space(self) -> int: ...
    def clear(self) -> None: ...
    def first_key_value(self) -> Optional[Tuple[bytes, bytes]]: ...
    def last_key_value(self) -> Optional[Tuple[bytes, bytes]]: ...
    def iter(self, *, reverse: bool = False, keys_only: bool = False) -> Iter: ...
    def prefix(self, prefix: bytes, *, reverse: bool = False, keys_only: bool = False) -> Iter: ...
    def range(
        self, start: Optional[bytes] = None, end: Optional[bytes] = None, *, reverse: bool = False, keys_only: bool = False
    ) -> Iter: ...
    def __getitem__(self, key: bytes) -> bytes: ...
    def __setitem__(self, key: bytes, value: bytes) -> None: ...
    def __delitem__(self, key: bytes) -> None: ...
    def __contains__(self, key: bytes) -> bool: ...

class Batch:
    def insert(self, keyspace: Keyspace, key: bytes, value: bytes) -> None: ...
    def remove(self, keyspace: Keyspace, key: bytes) -> None: ...
    def commit(self) -> None: ...
    def __len__(self) -> int: ...
    def __enter__(self) -> "Batch": ...
    def __exit__(self, exc_type: object, exc: object, tb: object) -> None: ...

class Database:
    def __init__(
        self,
        path: Union[str, PathLike[str]],
        *,
        cache_size: Optional[int] = None,
        worker_threads: Optional[int] = None,
        temporary: bool = False,
    ) -> None: ...
    def keyspace(self, name: str, *, max_memtable_size: Optional[int] = None, kv_separation: bool = False) -> Keyspace: ...
    def keyspace_exists(self, name: str) -> bool: ...
    def keyspace_count(self) -> int: ...
    def list_keyspace_names(self) -> list[str]: ...
    def delete_keyspace(self, keyspace: Keyspace) -> None: ...
    def batch(self) -> Batch: ...
    def persist(self, mode: PersistMode = "sync_all") -> None: ...
    def disk_space(self) -> int: ...
    def __enter__(self) -> "Database": ...
    def __exit__(self, exc_type: object, exc: object, tb: object) -> None: ...
